/* adif_test.c — M2 gate (log-adif-test): parse basics, a real-world quirks
 * corpus, unknown-field preservation, band-from-freq, bad-record and dup
 * accounting, input that is not ADIF at all, deterministic export format and
 * a byte-stable round trip.
 *
 * Part of log-for-linux. GPL-3.0-or-later.
 */
#include "adif.h"
#include "contest.h"

#include <glib/gstdio.h>
#include <string.h>

static LogflStore *
mem_store (void)
{
  GError *err = NULL;
  LogflStore *s = logfl_store_open (":memory:", &err);
  g_assert_no_error (err);
  return s;
}

static LogflQso *
single (LogflStore *s)
{
  GError *err = NULL;
  GPtrArray *l = logfl_store_list (s, NULL, &err);
  g_assert_no_error (err);
  g_assert_cmpuint (l->len, ==, 1);
  LogflQso *q = logfl_qso_copy (l->pdata[0]);
  g_ptr_array_unref (l);
  return q;
}

static void
test_parse_basic (void)
{
  GError *err = NULL;
  LogflStore *s = mem_store ();
  LogflAdifReport rep;

  const char *adif =
    "Generated by <sometool> on a rainy day\n"
    "<ADIF_VER:5>3.1.4<PROGRAMID:4>test<EOH>\n"
    "<QSO_DATE:8>20260718<TIME_ON:6>142530<CALL:5>OK1XY<BAND:3>40m"
    "<FREQ:6>7.0123<MODE:2>CW<RST_SENT:3>599<RST_RCVD:3>579<EOR>\n"
    "<QSO_DATE:8>20260718<TIME_ON:6>150000<CALL:6>DL2ABC<BAND:3>20m"
    "<MODE:3>SSB<NAME:5>Horst<EOR>\n";

  g_assert_true (logfl_adif_import_data (s, adif, -1, 0, &rep, &err));
  g_assert_no_error (err);
  g_assert_cmpuint (rep.n_imported, ==, 2);
  g_assert_cmpuint (rep.n_dup_skipped, ==, 0);
  g_assert_cmpuint (rep.n_bad, ==, 0);

  /* Header fields must NOT leak into the first record. */
  GPtrArray *l = logfl_store_list (s, NULL, &err);
  g_assert_cmpuint (l->len, ==, 2);
  const LogflQso *q = l->pdata[1];   /* oldest = first record */
  g_assert_cmpstr (q->call, ==, "OK1XY");
  g_assert_cmpfloat (q->freq, ==, 7.0123);
  g_assert_cmpstr (q->rst_rcvd, ==, "579");
  g_assert_null (q->extras);
  /* 20260718 14:25:30 UTC */
  GDateTime *dt = g_date_time_new_from_unix_utc (q->ts);
  char *iso = g_date_time_format (dt, "%Y%m%d %H%M%S");
  g_assert_cmpstr (iso, ==, "20260718 142530");
  g_free (iso);
  g_date_time_unref (dt);
  g_ptr_array_unref (l);
  logfl_store_close (s);
}

static void
test_quirks_corpus (void)
{
  GError *err = NULL;
  LogflStore *s = mem_store ();
  LogflAdifReport rep;

  /* No <EOH> (file starts with a field), lowercase tags, CRLF endings,
   * :type suffixes, odd whitespace, garbage between fields, 4-digit
   * TIME_ON, and a final record without <EOR>. */
  const char *adif =
    "<call:5:S>ok1xy \r\n"
    "  <qso_date:8:D>20260718<time_on:4>1425\r\n"
    "!!random noise!! <band:3>40M<mode:2:M>cw<eor>\r\n"
    "<CALL:6>DL2ABC<QSO_DATE:8>20260719<TIME_ON:6>091500"
    "<BAND:3>20m<MODE:3>SSB";

  g_assert_true (logfl_adif_import_data (s, adif, -1, 0, &rep, &err));
  g_assert_no_error (err);
  g_assert_cmpuint (rep.n_imported, ==, 2);
  g_assert_cmpuint (rep.n_bad, ==, 0);

  GPtrArray *l = logfl_store_list (s, NULL, &err);
  const LogflQso *q = l->pdata[1];
  g_assert_cmpstr (q->call, ==, "OK1XY");   /* normalized */
  g_assert_cmpstr (q->band, ==, "40m");
  g_assert_cmpstr (q->mode, ==, "CW");
  GDateTime *dt = g_date_time_new_from_unix_utc (q->ts);
  char *iso = g_date_time_format (dt, "%H%M%S");
  g_assert_cmpstr (iso, ==, "142500");      /* 4-digit TIME_ON → :00 */
  g_free (iso);
  g_date_time_unref (dt);
  g_assert_cmpstr (((LogflQso *) l->pdata[0])->call, ==, "DL2ABC");
  g_ptr_array_unref (l);
  logfl_store_close (s);
}

static void
test_unknown_fields_preserved (void)
{
  GError *err = NULL;
  LogflStore *s = mem_store ();
  LogflAdifReport rep;

  const char *adif =
    "<QSO_DATE:8>20260718<TIME_ON:6>142530<CALL:5>OK1XY<BAND:3>40m"
    "<MODE:2>CW<iota:6>EU-013<APP_LOGFL_X:3>abc<CONTEST_ID:4>TEST<EOR>\n";

  g_assert_true (logfl_adif_import_data (s, adif, -1, 0, &rep, &err));
  g_assert_cmpuint (rep.n_imported, ==, 1);

  LogflQso *q = single (s);
  g_assert_cmpstr (q->extras, ==,
                   "<IOTA:6>EU-013<APP_LOGFL_X:3>abc<CONTEST_ID:4>TEST");
  logfl_qso_free (q);

  /* …and they come back out verbatim. */
  char *out = logfl_adif_export_data (s, NULL, NULL, &err);
  g_assert_no_error (err);
  g_assert_nonnull (strstr (out,
      "<IOTA:6>EU-013<APP_LOGFL_X:3>abc<CONTEST_ID:4>TEST<EOR>"));
  g_free (out);
  logfl_store_close (s);
}

static void
test_band_from_freq (void)
{
  GError *err = NULL;
  LogflStore *s = mem_store ();
  LogflAdifReport rep;

  /* First record: FREQ only → band derived. Second: neither → bad. */
  const char *adif =
    "<QSO_DATE:8>20260718<TIME_ON:4>1425<CALL:5>OK1XY<FREQ:6>7.0123"
    "<MODE:2>CW<EOR>"
    "<QSO_DATE:8>20260718<TIME_ON:4>1500<CALL:6>DL2ABC<MODE:2>CW<EOR>";

  g_assert_true (logfl_adif_import_data (s, adif, -1, 0, &rep, &err));
  g_assert_cmpuint (rep.n_imported, ==, 1);
  g_assert_cmpuint (rep.n_bad, ==, 1);

  LogflQso *q = single (s);
  g_assert_cmpstr (q->band, ==, "40m");
  logfl_qso_free (q);
  logfl_store_close (s);

  /* Spot checks on the table itself. */
  g_assert_cmpstr (logfl_adif_band_for_freq (14.074), ==, "20m");
  g_assert_cmpstr (logfl_adif_band_for_freq (144.3), ==, "2m");
  g_assert_cmpstr (logfl_adif_band_for_freq (1.296), ==, NULL);
  g_assert_null (logfl_adif_band_for_freq (9.5));   /* broadcast, not ham */
}

static void
test_bad_records (void)
{
  GError *err = NULL;
  LogflStore *s = mem_store ();
  LogflAdifReport rep;

  const char *adif =
    /* no call */
    "<QSO_DATE:8>20260718<TIME_ON:4>1400<BAND:3>40m<MODE:2>CW<EOR>"
    /* no date */
    "<CALL:5>OK1AA<BAND:3>40m<MODE:2>CW<EOR>"
    /* rubbish date */
    "<QSO_DATE:8>2026wxyz<TIME_ON:4>1400<CALL:5>OK1BB<BAND:3>40m"
    "<MODE:2>CW<EOR>"
    /* no mode */
    "<QSO_DATE:8>20260718<TIME_ON:4>1400<CALL:5>OK1CC<BAND:3>40m<EOR>"
    /* the good one */
    "<QSO_DATE:8>20260718<TIME_ON:4>1400<CALL:5>OK1DD<BAND:3>40m"
    "<MODE:2>CW<EOR>"
    /* declared length runs past EOF → broken, not imported */
    "<QSO_DATE:8>20260718<TIME_ON:4>1500<CALL:5>OK1EE<BAND:3>40m"
    "<MODE:2>CW<COMMENT:500>oops";

  g_assert_true (logfl_adif_import_data (s, adif, -1, 0, &rep, &err));
  g_assert_no_error (err);
  g_assert_cmpuint (rep.n_imported, ==, 1);
  g_assert_cmpuint (rep.n_bad, ==, 5);

  LogflQso *q = single (s);
  g_assert_cmpstr (q->call, ==, "OK1DD");
  logfl_qso_free (q);
  logfl_store_close (s);
}

/* A file that is not ADIF at all is not an error: the import succeeds with
 * nothing imported and the store untouched — the app then reports the zero
 * counts instead of failing. */
static void
test_not_adif (void)
{
  GError *err = NULL;
  LogflStore *s = mem_store ();
  LogflAdifReport rep;

  const char *text = "this is not an ADIF file\njust two lines of text\n";
  g_assert_true (logfl_adif_import_data (s, text, -1, 0, &rep, &err));
  g_assert_no_error (err);
  g_assert_cmpuint (rep.n_imported, ==, 0);
  g_assert_cmpuint (rep.n_dup_skipped, ==, 0);
  g_assert_cmpuint (rep.n_bad, ==, 0);

  g_assert_true (logfl_adif_import_data (s, "", 0, 0, &rep, &err));
  g_assert_no_error (err);
  g_assert_cmpuint (rep.n_imported, ==, 0);
  g_assert_cmpuint (rep.n_bad, ==, 0);

  /* Binary junk: NULs, high bytes, stray and unterminated angle brackets,
   * a length that is not a number, one that runs past the end. */
  const char junk[] =
    "<\x00\xff\xfe><<>>\x89PNG\r\n\x1a\n<:>< :9><CALL:x>OK1AA<\x01:3:\x02>"
    "\x00\x00<EOR\x00><CALL:99999>OK";
  g_assert_true (logfl_adif_import_data (s, junk, (gssize) sizeof junk - 1,
                                         0, &rep, &err));
  g_assert_no_error (err);
  g_assert_cmpuint (rep.n_imported, ==, 0);

  GPtrArray *l = logfl_store_list (s, NULL, &err);
  g_assert_no_error (err);
  g_assert_cmpuint (l->len, ==, 0);
  g_ptr_array_unref (l);
  logfl_store_close (s);
}

static void
test_dup_skip (void)
{
  GError *err = NULL;
  LogflStore *s = mem_store ();
  LogflAdifReport rep;

  const char *adif =
    "<QSO_DATE:8>20260718<TIME_ON:6>142530<CALL:5>OK1XY<BAND:3>40m"
    "<MODE:2>CW<EOR>"
    /* same QSO 60 s later — intra-file dup within a 300 s window */
    "<QSO_DATE:8>20260718<TIME_ON:6>142630<CALL:5>OK1XY<BAND:3>40m"
    "<MODE:2>CW<EOR>";

  g_assert_true (logfl_adif_import_data (s, adif, -1, 300, &rep, &err));
  g_assert_cmpuint (rep.n_imported, ==, 1);
  g_assert_cmpuint (rep.n_dup_skipped, ==, 1);

  /* Whole-file re-import: everything is a dup. */
  g_assert_true (logfl_adif_import_data (s, adif, -1, 300, &rep, &err));
  g_assert_cmpuint (rep.n_imported, ==, 0);
  g_assert_cmpuint (rep.n_dup_skipped, ==, 2);

  /* Window 0: only the identical timestamp is a dup, the +60 s twin lands. */
  g_assert_true (logfl_adif_import_data (s, adif, -1, 0, &rep, &err));
  g_assert_cmpuint (rep.n_imported, ==, 1);
  g_assert_cmpuint (rep.n_dup_skipped, ==, 1);

  logfl_store_close (s);
}

/* CQ WW RTTY, the state alone in the exchange: CQZ goes out from the
 * state (logfl_exch_missing_cq_zone); a QSO that carries its CQZ already
 * gets it once, a QSO outside any contest gets none. */
static void
test_cqz_from_state (void)
{
  GError *err = NULL;
  LogflStore *s = mem_store ();
  guint n = 0;
  const LogflContestPreset *p = logfl_contest_presets (&n);
  const LogflContestPreset *rtty = NULL;
  for (guint i = 0; i < n; i++)
    if (g_str_equal (p[i].name, "CQ WW RTTY"))
      rtty = &p[i];
  g_assert_nonnull (rtty);
  LogflContest *c = logfl_contest_new ();
  c->name = g_strdup ("CQ WW RTTY 2026");
  c->adif_id = g_strdup (rtty->adif_id);
  c->exch_def = g_strdup (rtty->exch_def);
  g_assert_true (logfl_store_contest_add (s, c, &err));
  gint64 id = c->id;
  logfl_contest_free (c);

  LogflQso *q = logfl_qso_new ();
  q->call = g_strdup ("W1XYZ");
  q->band = g_strdup ("20m");
  q->mode = g_strdup ("RTTY");
  q->ts = 1790380800;
  q->contest_ref = id;
  q->srx_string = g_strdup ("MA");
  q->extras = g_strdup ("<STATE:2>MA");
  g_assert_true (logfl_store_add (s, q, &err));
  g_free (q->call);
  q->call = g_strdup ("K1AB");
  q->ts += 60;
  g_free (q->srx_string);
  q->srx_string = g_strdup ("05 MA");
  g_free (q->extras);
  q->extras = g_strdup ("<CQZ:2>05<STATE:2>MA");
  g_assert_true (logfl_store_add (s, q, &err));
  g_free (q->call);
  q->call = g_strdup ("DL1AB");
  q->ts += 60;
  q->contest_ref = 0;
  g_free (q->srx_string);
  q->srx_string = g_strdup ("MA");
  g_free (q->extras);
  q->extras = NULL;
  g_assert_true (logfl_store_add (s, q, &err));
  logfl_qso_free (q);

  char *out = logfl_adif_export_data (s, NULL, &n, &err);
  g_assert_no_error (err);
  g_assert_cmpuint (n, ==, 3);
  g_assert_nonnull (strstr (out, "<CALL:5>W1XYZ"));
  g_assert_nonnull (strstr (out, "<SRX_STRING:2>MA<STATE:2>MA<CQZ:1>5<EOR>"));
  g_assert_nonnull (strstr (out, "<SRX_STRING:5>05 MA<CQZ:2>05<STATE:2>MA<EOR>"));
  g_assert_nonnull (strstr (out, "<CALL:5>DL1AB"));
  g_assert_nonnull (strstr (out, "<SRX_STRING:2>MA<EOR>"));
  g_free (out);
  logfl_store_close (s);
}

static void
test_export_format (void)
{
  GError *err = NULL;
  LogflStore *s = mem_store ();

  LogflQso *q = logfl_qso_new ();
  q->call = g_strdup ("OK1XY");
  q->band = g_strdup ("40m");
  q->mode = g_strdup ("CW");
  q->ts = 1784384730;          /* 2026-07-18 14:25:30 UTC */
  q->freq = 7.0123;
  q->tx_pwr = 100;
  q->rst_sent = g_strdup ("599");
  g_assert_true (logfl_store_add (s, q, &err));
  logfl_qso_free (q);

  guint n = 0;
  char *out = logfl_adif_export_data (s, NULL, &n, &err);
  g_assert_no_error (err);
  g_assert_cmpuint (n, ==, 1);
  g_assert_true (g_str_has_prefix (out, "log-for-linux ADIF export\n"
                                        "<ADIF_VER:5>3.1.4"));
  g_assert_nonnull (strstr (out, "<EOH>\n"));
  g_assert_nonnull (strstr (out,
      "<QSO_DATE:8>20260718<TIME_ON:6>142530<CALL:5>OK1XY<BAND:3>40m"
      "<FREQ:6>7.0123<MODE:2>CW<RST_SENT:3>599<TX_PWR:3>100<EOR>\n"));
  g_free (out);
  logfl_store_close (s);
}

static void
test_roundtrip_stable (void)
{
  GError *err = NULL;
  LogflStore *a = mem_store ();
  LogflAdifReport rep;

  /* A log with extras, UTF-8, multiline comment and unset fields. */
  const char *adif =
    "<QSO_DATE:8>20260710<TIME_ON:6>070102<CALL:5>SM5XY<BAND:3>20m"
    "<MODE:3>FT8<GRIDSQUARE:4>JO89<NAME:6>\xc3\x85ke B<IOTA:6>EU-013<EOR>"
    "<QSO_DATE:8>20260711<TIME_ON:6>210000<CALL:6>OK1JIR<BAND:3>80m"
    "<MODE:2>CW<NAME:6>Ji\xc5\x99\xc3\xad<COMMENT:8>line\none<EOR>"
    "<QSO_DATE:8>20260712<TIME_ON:6>120000<CALL:4>W1AW<BAND:3>15m"
    "<MODE:3>SSB<TX_PWR:3>500<APP_X_Y:2>zz<EOR>";

  g_assert_true (logfl_adif_import_data (a, adif, -1, 0, &rep, &err));
  g_assert_cmpuint (rep.n_imported, ==, 3);
  g_assert_cmpuint (rep.n_bad, ==, 0);

  char *e1 = logfl_adif_export_data (a, NULL, NULL, &err);
  g_assert_no_error (err);

  LogflStore *b = mem_store ();
  g_assert_true (logfl_adif_import_data (b, e1, -1, 0, &rep, &err));
  g_assert_cmpuint (rep.n_imported, ==, 3);
  g_assert_cmpuint (rep.n_bad, ==, 0);
  char *e2 = logfl_adif_export_data (b, NULL, NULL, &err);
  g_assert_no_error (err);

  /* Byte-identical: nothing lost, nothing reshaped on the second pass. */
  g_assert_cmpstr (e1, ==, e2);
  g_assert_nonnull (strstr (e2, "<NAME:6>Ji\xc5\x99\xc3\xad"));
  g_assert_nonnull (strstr (e2, "<COMMENT:8>line\none"));
  g_assert_nonnull (strstr (e2, "<APP_X_Y:2>zz"));

  g_free (e1);
  g_free (e2);
  logfl_store_close (a);
  logfl_store_close (b);
}

static void
test_file_io (void)
{
  GError *err = NULL;
  LogflStore *s = mem_store ();
  LogflAdifReport rep;

  const char *adif =
    "<QSO_DATE:8>20260718<TIME_ON:4>1425<CALL:5>OK1XY<BAND:3>40m"
    "<MODE:2>CW<EOR>";
  g_assert_true (logfl_adif_import_data (s, adif, -1, 0, &rep, &err));

  char *dir = g_dir_make_tmp ("logfl-adif-XXXXXX", &err);
  g_assert_no_error (err);
  char *path = g_build_filename (dir, "export.adi", NULL);

  guint n = 0;
  g_assert_true (logfl_adif_export_file (s, path, NULL, &n, &err));
  g_assert_cmpuint (n, ==, 1);

  LogflStore *b = mem_store ();
  g_assert_true (logfl_adif_import_file (b, path, 0, &rep, &err));
  g_assert_cmpuint (rep.n_imported, ==, 1);
  logfl_store_close (b);

  g_assert_false (logfl_adif_import_file (s, "/nonexistent.adi", 0,
                                          &rep, &err));
  g_assert_nonnull (err);
  g_clear_error (&err);

  g_assert_cmpint (g_unlink (path), ==, 0);
  g_assert_cmpint (g_rmdir (dir), ==, 0);
  g_free (path);
  g_free (dir);
  logfl_store_close (s);
}

int
main (int argc, char **argv)
{
  g_test_init (&argc, &argv, NULL);
  g_test_add_func ("/adif/parse-basic", test_parse_basic);
  g_test_add_func ("/adif/quirks-corpus", test_quirks_corpus);
  g_test_add_func ("/adif/unknown-fields-preserved",
                   test_unknown_fields_preserved);
  g_test_add_func ("/adif/band-from-freq", test_band_from_freq);
  g_test_add_func ("/adif/bad-records", test_bad_records);
  g_test_add_func ("/adif/not-adif", test_not_adif);
  g_test_add_func ("/adif/dup-skip", test_dup_skip);
  g_test_add_func ("/adif/export-format", test_export_format);
  g_test_add_func ("/adif/cqz-from-state", test_cqz_from_state);
  g_test_add_func ("/adif/roundtrip-stable", test_roundtrip_stable);
  g_test_add_func ("/adif/file-io", test_file_io);
  return g_test_run ();
}
